name: Build and Publish

on: [ push, pull_request ]

jobs:
  build:
    name: Build modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info build

      - uses: actions/upload-artifact@v2
        name: Upload Core
        with:
          name: Gateway
          path: core/build/libs/
